### ISSUE TITLE
Add data sources

### ISSUE THREAD

**Issue by cameronattard** [suzuki-shunsuke/go-graylog#109]
It would be really helpful if there were data sources for resources like streams and index sets so you could refer to resources managed outside of Terraform without having to manually pass resource ids as variables.

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback!
Although I'm not familiar with develpment of data sources, I will check this.

* https://www.terraform.io/docs/extend/writing-custom-providers.html#data-sources
* https://www.terraform.io/docs/configuration/data-sources.html

**Comment by suzuki-shunsuke** [comment]
I have added data sources of IndexSet and Stream.
Please use terraform-provider-graylog >= v3.1.0 .

**Comment by Luubosi** [comment]
could you add data source for resource_dashboard, it would be great, 
ID of stream and dashboard is very useful for role managment.
thanks :)

**Comment by suzuki-shunsuke** [comment]
@Luubosi Thank you for your feedback.
I have created the pull request #184 .

**Comment by suzuki-shunsuke** [comment]
I have released [v8.1.0](https://github.com/suzuki-shunsuke/go-graylog/releases/tag/v8.1.0) and 
 [new Docker image](https://quay.io/repository/suzuki_shunsuke/terraform-graylog?tab=tags).

**Comment by suzuki-shunsuke** [comment]
I close this issue.
If you need the data source for the other resource, please create an issue.
