### ISSUE TITLE
Support data source of graylog_index_set

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/go-graylog#110]
This is a sub issue of #109 .

* https://www.terraform.io/docs/extend/writing-custom-providers.html#data-sources
* https://www.terraform.io/docs/configuration/data-sources.html

**Comment by suzuki-shunsuke** [comment]
@cameronattard 

I have created the data source of IndexSet #111 .

Could you check whether this is what you want?

https://github.com/suzuki-shunsuke/go-graylog/blob/feat/issue-110/terraform/docs/data_source_index_set.md

I will also support other data sources such as stream.

Thanks!

**Comment by cameronattard** [comment]
@suzuki-shunsuke that's exactly what I want, thanks so much!
