### ISSUE TITLE
Add static fields for inputs

### ISSUE THREAD

**Issue by Luubosi** [suzuki-shunsuke/go-graylog#118]
Hi,
it would be great to add "static fields" for inputs.
Enhancement for graylog input.
request url:
https://ip:9000/api/system/inputs/input_id

{
  "title": "input name",
  "global": true,
  "name": "GELF UDP",
  "content_pack": null,
  "created_at": "2017-05-31T08:48:06.536Z",
  "type": "org.graylog2.inputs.gelf.udp.GELFUDPInput",
  "creator_user_id": "admin",
  "attributes": {
    "override_source": null,
    "recv_buffer_size": 262144,
    "bind_address": "0.0.0.0",
    "port": port,
    "decompress_size_limit": 8388608
  },
  **"static_fields": {
    "input_field": "input_field"
  },**
  "node": null,
  "id": "id"
}

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback!
Although I didn't add a "static_fields" because I didn't know how to set static fields, I will check it.

**Comment by suzuki-shunsuke** [comment]
Oh, I found how to add static fields.

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/13323303/60142592-65127180-97f5-11e9-9df0-55638482b91d.png">

**Comment by suzuki-shunsuke** [comment]
Release [v3.2.0](https://github.com/suzuki-shunsuke/go-graylog/releases/tag/v3.2.0).

**Comment by Luubosi** [comment]
Hi, thanks, this is great project :)

**Comment by Luubosi** [comment]
Hi,
please, could you add definition static field here, too.
https://github.com/suzuki-shunsuke/example/blob/master/graylog-terraform/input.tf

I do not understand this type:
static_fields | map[string]string

 i do not know to define variable for this type.
thanks for clarification.

**Comment by suzuki-shunsuke** [comment]
Unfortunately you can't define the field `static_fields` in the `graylog_input` resource.
This field is read-only.
Currently `go-graylog` doesn't support to change static fields yet
because Graylog's POST and PUT API don't support it.
In order to change static fields, `go-graylog` has to support the StaticFields API #119 .
I will support it.

Thanks.

**Comment by suzuki-shunsuke** [comment]
https://github.com/suzuki-shunsuke/go-graylog/pull/121

**Comment by suzuki-shunsuke** [comment]
Release [v3.3.0](https://github.com/suzuki-shunsuke/go-graylog/releases/tag/v3.3.0) .

https://github.com/suzuki-shunsuke/go-graylog/blob/master/terraform/docs/input_static_fields.md

**Comment by suzuki-shunsuke** [comment]
I close this issue.
Please see https://github.com/suzuki-shunsuke/go-graylog/blob/master/terraform/docs/input_static_fields.md .
