### ISSUE TITLE
Using graylog api token

### ISSUE THREAD

**Issue by gkocur** [suzuki-shunsuke/go-graylog#152]
I was trying to use API token in place of password as described in readme, but it gave me `401`.
According to graylog 3 documentation:

> The received access token can now be used as username in a request to the Graylog REST API using Basic Auth together with the literal password token.

And indeed - if I used token as username and `token` literal as password it worked.
Is it a documentation issue?

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback.
Sorry but the description of `auth_password` is wrong.
We have to fix it.

https://github.com/suzuki-shunsuke/go-graylog/tree/master/terraform#required

name | Environment variable | description
-- | -- | --
web_endpoint_uri | GRAYLOG_WEB_ENDPOINT_URI | API endpoint, for example https://graylog.example.com/api
auth_name | GRAYLOG_AUTH_NAME | Username
auth_password | GRAYLOG_AUTH_PASSWORD | Password or API token

**Comment by suzuki-shunsuke** [comment]
https://docs.graylog.org/en/latest/pages/configuration/rest_api.html#creating-and-using-access-token

```
auth_name = "<API token>"
auth_password = "token"  # literal
```

**Comment by suzuki-shunsuke** [comment]
https://github.com/suzuki-shunsuke/go-graylog/pull/153

**Comment by suzuki-shunsuke** [comment]
Would you check #153 ?

**Comment by suzuki-shunsuke** [comment]
I close this issue because #153 is merged.

Thank you for your feedback!
