### ISSUE TITLE
Error when graylog object deleted manually

### ISSUE THREAD

**Issue by gkocur** [suzuki-shunsuke/go-graylog#154]
Hi!

Let's imagine the scenario:

1. Create a stream with terraform
2. Create a stream rule for this stream with terraform
3. Manually delete the stream
4. Run `terraform plan`.

The terraform command exits with error:
`Error: graylog API error: GET https://graylog.domain.com/api/streams/5d63828b0844a200202450b5 404: Stream <5d63828b0844a200202450b5> not found!`

The only workaround is to remove the stream rule and the stream form the state file and re-run `terraform apply`.

I think the correct behaviour in such case is to re-create the stream and update the stream rule with the new stream id.

**Comment by gkocur** [comment]
BTW the same is for other objects when one object has an is of other in definition, for example input and extractor.

**Comment by suzuki-shunsuke** [comment]
> I think the correct behaviour in such case is to re-create the stream and update the stream rule with the new stream id.

This behavior is a Terraform's specification, and doesn't have nothing to do with this project.
If you deleted manually the resource managed by Terraform, you have to delete the resource from the state file.

**Comment by gkocur** [comment]
Thank you very much for prompt answer!
I just tested it with GCP instance, and when I deleted it manually it was re-created.
AFAIK aws provider works similar - re-creates manually deleted resources.
I also found this PR: https://github.com/terraform-providers/terraform-provider-vsphere/pull/321 for vSphere provider - if I understand it correctly they simply remove the manually delated objects form state file.

IMVHO It would be super convenient to be able to configure graylog with terraform as well as manually (for example to test some setting).

**Comment by suzuki-shunsuke** [comment]
Thank you for your information!
I will check it later.

**Comment by gkocur** [comment]
Thank you! You do a great job!

**Comment by suzuki-shunsuke** [comment]
Ok. I got it.
[My previous post](https://github.com/suzuki-shunsuke/go-graylog/issues/154#issuecomment-524754558) is wrong.

https://www.terraform.io/docs/extend/writing-custom-providers.html#implementing-read

> If the ID is updated to blank, this tells Terraform the resource no longer exists (maybe it was destroyed out of band).
> Just like the destroy callback, the Read function should gracefully handle this case.

I will fix.

**Comment by suzuki-shunsuke** [comment]
I have created the pull request #155

**Comment by suzuki-shunsuke** [comment]
I have released the new version v7.0.0 and Docker image.
Please check.

* https://github.com/suzuki-shunsuke/go-graylog/releases/tag/v7.0.0
* https://quay.io/repository/suzuki_shunsuke/terraform-graylog?tab=tags

**Comment by gkocur** [comment]
You are awesome! Works great so far, thank you!
