### ISSUE TITLE
Support Dashboard Widget API

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/go-graylog#20]

**Comment by suzuki-shunsuke** [comment]
```
Dashboards/Widgets : Manage widgets of an existing dashboard 
POST /dashboards/{dashboardId}/widgets Add a widget to a dashboard
PUT /dashboards/{dashboardId}/widgets/{widgetId} Update a widget
GET /dashboards/{dashboardId}/widgets/{widgetId} Get a widget
DELETE /dashboards/{dashboardId}/widgets/{widgetId} Delete a widget
PUT /dashboards/{dashboardId}/widgets/{widgetId}/cachetime Update cache time of a widget
PUT /dashboards/{dashboardId}/widgets/{widgetId}/description Update description of a widget
GET /dashboards/{dashboardId}/widgets/{widgetId}/value Get a single widget value.
```

http://127.0.0.1:9000/api/dashboards/5b65868b08813b0001777af3/widgets/dbe8ebfc-a9e3-45d6-a72c-18ff7fa1761f

```json
{
  "id": "dbe8ebfc-a9e3-45d6-a72c-18ff7fa1761f",
  "description": "Stream search result count",
  "type": "STREAM_SEARCH_RESULT_COUNT",
  "config": {
    "timerange": {
      "type": "relative",
      "range": 300
    },
    "lower_is_better": true,
    "stream_id": "5b39838b08813b00011ec334",
    "trend": true,
    "query": ""
  },
  "cache_time": 10,
  "creator_user_id": "admin"
}
```

**Comment by suzuki-shunsuke** [comment]
GET /dashboards/{dashboardId}/widgets/{widgetId} Get a widget

http://127.0.0.1:9000/api/dashboards/5b65868b08813b0001777af3/widgets/dbe8ebfc-a9e3-45d6-a72c-18ff7fa1761f

```json
{
  "id": "dbe8ebfc-a9e3-45d6-a72c-18ff7fa1761f",
  "description": "Stream search result count",
  "type": "STREAM_SEARCH_RESULT_COUNT",
  "config": {
    "timerange": {
      "type": "relative",
      "range": 300
    },
    "lower_is_better": true,
    "stream_id": "5b39838b08813b00011ec334",
    "trend": true,
    "query": ""
  },
  "cache_time": 10,
  "creator_user_id": "admin"
}
```

**Comment by suzuki-shunsuke** [comment]
POST /dashboards/{dashboardId}/widgets Add a widget to a dashboard

request

```json
{
  "description": "Stream search result count",
  "type": "STREAM_SEARCH_RESULT_COUNT",
  "config": {
    "timerange": {
      "type": "relative",
      "range": 300
    },
    "lower_is_better": true,
    "stream_id": "5b39838b08813b00011ec334",
    "trend": true,
    "query": ""
  },
  "cache_time": 10
}
```

response

```json
{
  "widget_id": "ee2532ce-6995-4b8b-8c2c-4de327c6cce4"
}
```

allowed fields: type, description, config, cache_time

400

```json
{
  "type": "ApiError",
  "message": "Unable to map property creator_user_id.\nKnown properties include: type, description, config, cache_time"
}
```

**Comment by suzuki-shunsuke** [comment]
PUT /dashboards/{dashboardId}/widgets/{widgetId} Update a widget

request

```json
{
  "type": "STREAM_SEARCH_RESULT_COUNT",
  "description": "Stream search result count",
  "config": {
    "timerange": {
      "type": "relative",
      "range": 300
    },
    "lower_is_better": true,
    "stream_id": "5b39838b08813b00011ec334",
    "trend": true,
    "query": ""
  }
}
```

response: 204 no content

* required fields
  * description
  * type
  * config
* allowed fields
  * cache_time

**Comment by suzuki-shunsuke** [comment]
DELETE /dashboards/{dashboardId}/widgets/{widgetId} Delete a widget

204 no content

**Comment by suzuki-shunsuke** [comment]
PUT /dashboards/{dashboardId}/widgets/{widgetId}/cachetime Update cache time of a widget

request

required: nothing

response: 204 no content

**Comment by suzuki-shunsuke** [comment]
PUT /dashboards/{dashboardId}/widgets/{widgetId}/description Update description of a widget

request

* required
  * description 500
  * cache_time

response: 204 no content

**Comment by suzuki-shunsuke** [comment]
GET /dashboards/{dashboardId}/widgets/{widgetId}/value Get a single widget value.

response: 200

```json
{
  "result": 150,
  "took_ms": 0,
  "calculated_at": "2018-09-29T09:33:56.502Z"
}
```

**Comment by suzuki-shunsuke** [comment]
https://github.com/suzuki-shunsuke/go-graylog/pull/37
https://github.com/suzuki-shunsuke/go-graylog/pull/36

**Comment by gkocur** [comment]
I really appreciate you work, since the Graylog configuration is stored in MongoDB it's really hard to keep the config in VCS. This project seems to solve this problem!

Any plan to close this issue? I think the dashboard widgets is the one of most important missing parts of the provider.

Unfortunately, I'm not a golang programmer so can't help much here..

Thank you!

**Comment by suzuki-shunsuke** [comment]
@gkocur Thank you for your feedback!
I will deal with this issue this weekend.

Thank you.

**Comment by suzuki-shunsuke** [comment]
I have added the terraform provider resource "graylog_dashboard_widget".
https://github.com/suzuki-shunsuke/go-graylog/blob/master/terraform/docs/dashboard_widget.md

And I have released the new version [v4.0.0](https://github.com/suzuki-shunsuke/go-graylog/releases/tag/v4.0.0) and [the new Docker image](https://quay.io/repository/suzuki_shunsuke/terraform-graylog?tab=tags).

Thank you.

**Comment by suzuki-shunsuke** [comment]
Note that go-graylog doesn't support PUT /dashboards/{dashboardId}/positions API yet,
so we can't control the positions of widgets.

**Comment by suzuki-shunsuke** [comment]
PUT /dashboards/{dashboardId}/positions

request body

```json
{
  "positions": [
    {
      "id": "b3be33f5-0000-0000-0000-000000000000",
      "width": 2,
      "col": 6,
      "row": 1,
      "height": 3
    },
    {
      "id": "b3be33f5-0000-0000-0000-000000000001",
      "width": 4,
      "col": 1,
      "row": 1,
      "height": 2
    }
  ]
}
```

response 204 no content

**Comment by suzuki-shunsuke** [comment]
I have added the terraform provider resource "graylog_dashboard_widget_positions".

https://github.com/suzuki-shunsuke/go-graylog/blob/master/terraform/docs/dashboard_widget_positions.md

And I have released the new version [v4.1.0](https://github.com/suzuki-shunsuke/go-graylog/releases/tag/v4.1.0) and [the new Docker image](https://quay.io/repository/suzuki_shunsuke/terraform-graylog?tab=tags).

So you can manage the positions of the dashboard widgets with Terraform.

Thank you.

**Comment by gkocur** [comment]
It sounds very promising, will test it today, thank you very much for your work!

**Comment by suzuki-shunsuke** [comment]
Thank you for your test.
I'm looking forward to your feedback.

Thank you.

**Comment by suzuki-shunsuke** [comment]
I close this issue.
If you have any feedback, please create an issue.

Thank you.
