### ISSUE TITLE
Give ready only to only one stream with Role

### ISSUE THREAD

**Issue by saidogoid** [suzuki-shunsuke/go-graylog#236]
Hi,
I search on your code, and I didn't find any way to assign only one stream, instead of having all those on ready only to a user.

Something like this
```
# Create roles
resource "graylog_role" "backend" {
  name        = "backend-role"
  description = "Managed by Terraform"

  permissions = [
    "streams:read:5e25a81c193a490013f3266c",
  ]
}

# Create User and assign role
resource "graylog_user" "backend-users" {
  username    = "user"
  email       = "example@example.com"
  full_name   = "User Test"
  password    = "password"
  roles       = [
    "Reader",
    "backend-role",
  ]
}
```

Just do this on UI, and then runned `terraform apply` and copied the output.

Original example file:

```
resource "graylog_role" "backend" {
  name        = "backend-role"
  description = "Managed by Terraform"

  permissions = [
    "streams:read",
  ]
}
```

Any ideas on this ID generated? Maybe a output for `graylog_rule`?

**Comment by suzuki-shunsuke** [comment]
Does the following example help you?

```hcl
resource "graylog_stream" "test" {
  title         = "test"
  index_set_id  = "xxx"
  disabled      = true
  matching_type = "AND"
  description   = "test"
}

resource "graylog_role" "backend" {
  name        = "backend-role"
  description = "Managed by Terraform"

  permissions = [
    "streams:read:${graylog_stream.test.id}",
  ]
}
```

**Comment by saidogoid** [comment]
> 
> 
> Does the following example help you?
> 
> ```terraform
> resource "graylog_stream" "test" {
>   title         = "test"
>   index_set_id  = "xxx"
>   disabled      = true
>   matching_type = "AND"
>   description   = "test"
> }
> 
> resource "graylog_role" "backend" {
>   name        = "backend-role"
>   description = "Managed by Terraform"
> 
>   permissions = [
>     "streams:read:${graylog_stream.test.id}",
>   ]
> }
> 
> resource "graylog_user" "backend-users" {
>   username    = "user"
>   email       = "example@example.com"
>   full_name   = "User Test"
>   password    = "password"
>   roles       = [
>     "Reader",
>     graylog_role.backend.name,
>   ]
> }
> ```

Hi,
That's exactly that!
` "streams:read:${graylog_stream.test.id}",`
Thx, gj here!
