### ISSUE TITLE
Support Graylog 3.0

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/go-graylog#66]
https://www.graylog.org/post/announcing-graylog-v3-0-ga

We don't check Graylog 3.0 yet.

**Comment by ion-storm** [comment]
When do you plan on adding 3.0 support? Following your code, looks great!

**Comment by suzuki-shunsuke** [comment]
@ion-storm 
Thank you for your comment!
I'm glad you are interested in the project.

I will check whether go-graylog works in Graylog v3 in this weekend and
create issues when I will find them.

Thanks.

**Comment by suzuki-shunsuke** [comment]
resource | status
--- | ---
alarm_callback |
dashboard | 
dashboard_widget | 
index_set | 
index_set_stat | 
input | 
ldap_setting | 
ldap_group | 
pipeline | ok
pipeline_rule | ok
pipeline_connection | ok
role | ok
role_member | 
stream | ok
stream_alarm_callback | 
stream_alert_condition | 
stream_rule | 
user | 
collector_configuration |

**Comment by suzuki-shunsuke** [comment]
https://github.com/suzuki-shunsuke/go-graylog#support-of-graylog-v3

Please use [client.NewClientV3](https://godoc.org/github.com/suzuki-shunsuke/go-graylog/client#NewClientV3) instead of [client.NewClient](https://godoc.org/github.com/suzuki-shunsuke/go-graylog/client#NewClient) .

In the terraform provider, please set the variable `api_version` to `v3`.

https://github.com/suzuki-shunsuke/go-graylog/tree/master/terraform#optional

**Comment by cameronattard** [comment]
Thanks for acting on this so quickly @suzuki-shunsuke!

**Comment by suzuki-shunsuke** [comment]
We won't support Graylog v3 at graylog-mock-server.
We haven't developed it for a long time.
Originally we developed graylog-mock-server for test of client and terraform-provider-graylog.
We thought it is useful especially for test of terraform-provider-graylog at CI.
But we found that the development of graylog-mock-server is too expensive.

**Comment by suzuki-shunsuke** [comment]
We close the issue. If you find any problems about Graylog v3, please create issues.
Thanks.
